# I'm creating the Ec2 and R53 playbook here
# This playbook will create an EC2 instance and a Route 53 record for the instance
- name: create ec2 and R53
  hosts: localhost
  connection: local
  vars:
    ami_id:  ami-0220d79f3f480ecf5
    sg_id:  sg-0ca84109ed7b2fd6a
    zone_id: Z0643845MTWJNN2ZJCER
    domain_name: "daws86s.me"
    instances:
     - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"