# creating the frontend service by using the ansible-playbook.
- name: creating the frontend sever
  hosts: frontend
  become: yes
  task:
  - name: disable the default nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable the nginx 1.24
    ansible.builtin.command: dnf module enable the nginx:1.24 -y

  - name: install ngnix
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Remove the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: creating the html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: extract frontend application
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: delete default nginx conf
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copy nginx conf
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted # restarted if you have already started earlier
      enabled: yes