# Creating the rabbitmq service by using the ansible plugins
- name: creatin the rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks:
    - name: copy the rabbitmq repo # copying the rabbitmq repo 
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: installing the rabbitmq server
      ansible.builtin.package:
        name: rabbitmq-server
        state: present

    - name: start and enable the rabbitmq service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: create and give permission to the user # creating user and giving the permissions to the user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        permissions:
          - vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        state: present